### PR TITLE
2.1.0.0

### PR DESCRIPTION
**Pull request by lylehuber**
Added instrument type enumerated value.

### CODE REVIEW

**Review by rsjoyner — APPROVED** [review]
Updates appear to reasonable

**Comment by rsjoyner** [comment]
I "reviewed" the changes -- and they appear to be reasonable.
I "merged" the changes in the 2.1.0.0 Branch with Main.  So, life should be good.

**Comment by lylehuber** [comment]
And it’s now PDS4_CTLI_1L00_2100, is that correct?

Lyle


On Jan 11, 2024, at 10:26 AM, Ronald Joyner ***@***.***> wrote:

WARNING This email originated external to the NMSU email system. Do not click on links or open attachments unless you are sure the content is safe.


I "reviewed" the changes -- and they appear to be reasonable.
I "merged" the changes in the 2.1.0.0 Branch with Main. So, life should be good.

**Comment by jordanpadams** [comment]
@lylehuber unfortunately, no. In order for a GitHub release to be tagged, you need to include `release` in the branch, e.g. `release/2.1.0.0`

**Pull request merged**
